# version: '3.9'

networks:
  inception:
    name: inception

services:
  nginx:
    image: debian:latest
    container_name: nginx
    build: requirements/nginx/.
    volumes:
      - .wordpress:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress/.
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - .wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=wordpress_db
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=wordpress_password
      - WORDPRESS_DB_NAME=wordpress_db
    env_file:
      - .env
    networks:
      - inception
    restart: always