# version: '3.9'

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/rottbliss/42/inception/srcs/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/rottbliss/42/inception/srcs/data/mariadb
                        o: bind
                        type: none


networks:
  inception:
    name: inception

services:
  nginx:
    image: debian:latest
    container_name: nginx
    build: requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build: requirements/wordpress/.
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always