version: '3.9'
services:
  debian:
    image: debian:11
    container_name: debian_container
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
    ports:
      - "8080:80"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: always