# version: '3.9'

networks:
  inception:
    name: inception

services:
  nginx:
    image: debian:latest
    container_name: debian_container
    build: requirements/nginx/.
    volumes:
      - ./data:/data
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    volumes:
      - ./data:/data
    ports:
      - "8081:80"
    environment:
      - WORDPRESS_DB_HOST=wordpress_db
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=wordpress_password
      - WORDPRESS_DB_NAME=wordpress_db
    env_file:
      - .env
    networks:
      - inception
    restart: always